# Generated by Django 5.2.9 on 2025-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('A', 'All')], default='A', help_text='Who the user wants to see in dashboard', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('F', 'Woman')], max_length=20, null=True),
        ),
    ]
