# Generated by Django 5.2.9 on 2025-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_gender_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('A', 'All')], default='A', help_text='Who the user wants to see in dashboard', max_length=10),
        ),
    ]
