# Generated by Django 5.2.9 on 2025-12-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('A', 'All')], default='A', help_text='Who the user wants to see in dashboard', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('LT', 'Long-term partner'), ('SR', 'Serious daters'), ('FT', 'Free tonight'), ('ST', 'Short-term fun'), ('FR', 'Friendship'), ('UN', 'Not sure yet')], help_text="User's dating or social intention (Explore categories)", max_length=2, null=True),
        ),
    ]
