# Generated by Django 5.2.9 on 2025-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_gender_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('A', 'All')], default='A', help_text='Who the user wants to see in dashboard', max_length=1),
        ),
    ]
