# Generated by Django 5.2.9 on 2025-12-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_gender_alter_profile_looking_for'),
    ]

    operations = [
    ]
