# Generated by Django 5.2.9 on 2026-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20251229_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship_goal',
            field=models.CharField(choices=[('LT', 'Long-term partner'), ('SR', 'Serious daters'), ('FT', 'Free tonight'), ('ST', 'Short-term fun'), ('FR', 'Friendship'), ('UN', 'Not sure yet')], help_text="User's dating or social intention (Explore categories)", max_length=2, null=True),
        ),
    ]
