# Generated by Django 5.2.9 on 2026-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_relationship_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphoto',
            options={'ordering': ['-is_main', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='userphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
