# Generated by Django 5.2.9 on 2025-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expire_at',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='login', max_length=50),
        ),
    ]
