# Generated by Django 5.2.5 on 2025-08-23 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode_user_twofa_secret_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifytoken',
            old_name='expire_at',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
