# Generated by Django 5.2.9 on 2025-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_birthday_user_full_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('longterm', 'Long-term partner'), ('serious', 'Serious daters'), ('freetonight', 'Free tonight'), ('shortterm', 'Short-term fun')], help_text="User's dating intention (Explore categories)", max_length=20, null=True),
        ),
    ]
