# Generated by Django 5.2.9 on 2025-12-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_relationship_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('longterm', 'Long-term partner'), ('serious', 'Serious daters'), ('freetonight', 'Free tonight'), ('shortterm', 'Short-term fun'), ('friendship', 'Friendship'), ('unsure', 'Not sure yet')], help_text="User's dating or social intention (Explore categories)", max_length=20, null=True),
        ),
    ]
